### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by teddy4445** [lecture-developer/lecture_website_template#20]
Design issues across all the pages of the project. Will be added below:

**Comment by noamTzi** [comment]
### Design issues - front-office desktop version

Hey there :) so all in all, the website looks great! I have written down some issues I found:

1. **General**
- _1rem = 16 px_
- main indigo = #5A67D8
- _Grid fix_ - I fixed the grid on most of the handoff pages. It should be equal now on all pages. On the smallest desktop screen size we worked on (1440px), grid is: 5rem from top (80px), 12.5rem from each side (200px).
- _Design system update_ - I don't know if and how much you guys use it, but it's cleaner now.
- _The fonts sizes_ can also be found in the design system page, I believe this can be useful. All text that's not a title is 1rem (=16px), please make sure this is applied to the entire website:
**Research/single course/etc. pages font size template:**
-- Main headline - H1
-- main text (explanation of page) - 1rem
-- tab menu (optional)
---- secondary headlines - h3
---- subtitle - 1rem medium
---- text - 1rem
---- selection box text - 1rem
---- little text - 0.875rem
**Home page font size template:**
-- Main headline - H1
-- secondary headline - h2
-- text - 1rem
and then:
-- secondary headline - h2
-- text - 1rem
---- secondary headline - h3
---- text - 1rem

♥ notice - all links are based on the text so they are also 16px/1rem regular weight, but coloured in main indigo.

- _header links on hover_ - should be filled with main indigo.
- Is it possible to animate all elements when they are filled with colour? like you did on the one-page site, which was really cool. If possible, then please add a 250ms animation to the colour change whenever it happens, I think it'll look good.
- _icons_ - all right icons are in assets folder on google drive. Also, there should be a gap between them and their text (if present), of 0.5rem (8px). That's not equal in all pages. on hover, they behave like text links - they turn to main indigo.
- _breadcrumbs_ - we gave that up.
- _going through website_ - is it possible to make the page switch softer? When I switch pages, everything "jumps" a bit up and then quickly goes back to its place.

----------------------------------------
2. [**404 page**](https://teddy4445.github.io/lecture_website_template/404.html)
- please change it according to the grid.
- button: on hover - should be filled with main indigo colour, including its stroke, and text+arrow should turn white (now: it's stroke changes to blue, doesn't get filled).
on click/active/focused - should be filled with main indigo colour, including its stroke, and text+arrow should turn white (now: it's stroke changes to blue and filled with blue).

----------------------------------------
3. [**Home page**](https://teddy4445.github.io/lecture_website_template/)
- Change text size according to the design system.
- Fixed headlines issue - please change details part according to handoff page,
- Publication element:
-- I changed back the publication element - buttons of action switched places with labels on the bottom side of the element.
-- cite button's text is not centred to cite's icon.
-- labels are suppossed to be smaller and have a smaller gap between them, you may find the element specs at the handoff file.
-- It should allow "read more" only if there are more than 4 lines of text. Is it possible to do?

----------------------------------------
4. [**About page**](https://teddy4445.github.io/lecture_website_template/about.html)
- Change text size according to the design system.
- Fixed headlines issue - please change details part according to handoff page.
- Please remove breadcrumbs at top.
- tab menu:
-- please give more room to the titles according to its length. For example, if a word is 10 letters long, then its tab should be 16 letters long (like 3 extra letters that aren't visible from each side).
-- tabs' long bar should be 0.5rem high.
-- the gap between word and tab bar should be 0.rem as well.
-- tab text size should be 1rem.
-- can we animate the tab bars like the menu links on the one-page please? :)
- selection box:
-- the design is in the design system now (Dropdown).
-- please change the text to 1rem, let its arrow and stroke be visible, and lower the shadow.
-- on hover, its items should be filled with main indigo.

----------------------------------------
5. [**Publications page**](https://teddy4445.github.io/lecture_website_template/publications.html)
- Change text size according to the design system.
- Fixed headlines issue - please change details part according to handoff page.
- Please remove breadcrumbs at top.
- Order By, filter, years titles - all should be of type "small text" = 0.875rem, regular weight.
- Publication element: regard "publication element:" in section 3.

----------------------------------------
6. [**Research page**](https://teddy4445.github.io/lecture_website_template/research.html)
- Change text size according to the design system.
- Fixed headlines issue - please change details part according to handoff page.
- Please remove breadcrumbs at top.
- tab menu: regard "tab menu" in section 4.
- team section: if in last line team members' number % 3 != 0, please align team members of this line to the left.
- expand/minimize: not working. Also, in "work with me" tab, it's missing.

----------------------------------------
7. [**Courses page**](https://teddy4445.github.io/lecture_website_template/teaching.html)
- Please change url to "courses.html".
- Change text size according to the design system.
- Fixed headlines issue - please change details part according to handoff page.
- Please remove breadcrumbs at top.
- tab menu: regard "tab menu" in section 4.
- filter menu: no need for the text on selected button to turn bold. Also, it allows the user select just one filter, but the user may select some filters and not just one.

----------------------------------------
8. [**Single course page**](https://teddy4445.github.io/lecture_website_template/course-page.html?course_id=321)
- Change text size according to the design system.
- Fixed headlines issue - please change details part according to handoff page.
- Please remove breadcrumbs at top.
- tab menu: regard "tab menu" in section 4.

**Comment by Ayeletkel** [comment]
היי, אז מסתבר שכשהעתקתי את הטקסטים מהאתר הישן שלך שכחתי לבדוק אם יש טייפוז (סורי) ועכשיו מצאתי מלא טייפוז + עוד קצת טעויות קטנות של קפיטל לטרז וכאלה. ריכזתי אותם כאן:

https://docs.google.com/document/d/1ZTW5dpbAiJINafRdFuKrUNyZBe6Wi0KrQtY3GKw9LhQ/edit?usp=sharing

**Comment by noamTzi** [comment]
Hi, new design issues here, thanks for helping :)

- Top menu:
can we add a top menu indication like @Hadari23 did on the one-page website? (http://sphera.academy/#whoweare)

- In-page categories:
The space between the text and the line is not there anymore. Could you guys please change it to 8px (0.5rem) between the text and the grey/purple line? 
![image](https://user-images.githubusercontent.com/39398826/100645343-36cb8680-3345-11eb-90d5-4cfff06fc0fa.png)

- About page:
![image](https://user-images.githubusercontent.com/39398826/100638472-bdc83100-333c-11eb-9418-21c9ff624dd7.png)

Thank you <3
